# Generated by Django 2.0.5 on 2018-05-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade_Natal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade_Quartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comportamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_guerra', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_inclusao', models.DateField()),
                ('sangue', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('grau_instrucao', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=30)),
                ('nacionalidade', models.CharField(max_length=30)),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('obs', models.TextField()),
                ('cargo_funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cargo_Funcao')),
                ('comportamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Comportamento')),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_Quartel')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Patente'),
        ),
        migrations.AddField(
            model_name='militar',
            name='lotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='militar',
            name='naturalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_Natal'),
        ),
        migrations.AddField(
            model_name='militar',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Patente'),
        ),
        migrations.AddField(
            model_name='cidade_quartel',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cidade_natal',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cargo_funcao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Secao'),
        ),
    ]
