# Generated by Django 2.0.5 on 2018-07-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometro', models.CharField(max_length=50)),
                ('combustivel', models.CharField(max_length=50)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Area_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de prevenção',
            },
        ),
        migrations.CreateModel(
            name='Bairro_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bairros de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Bairro_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bairros de prevenções',
            },
        ),
        migrations.CreateModel(
            name='Cargo_Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cargos/funções',
            },
        ),
        migrations.CreateModel(
            name='Cidade_Natal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades onde residem militar(es)',
            },
        ),
        migrations.CreateModel(
            name='Cidade_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Cidade_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades de prevenções',
            },
        ),
        migrations.CreateModel(
            name='Cidade_Quartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades onde existe quartel',
            },
        ),
        migrations.CreateModel(
            name='Comportamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('data_parte', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['data_parte'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['data_inicio'],
                'verbose_name_plural': 'Férias',
            },
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_guerra', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_inclusao', models.DateField()),
                ('sangue', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('grau_instrucao', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=30)),
                ('nacionalidade', models.CharField(max_length=30)),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='militares_photo')),
                ('obs', models.TextField(blank=True)),
                ('cargo_funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cargo_Funcao')),
                ('comportamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Comportamento')),
            ],
            options={
                'ordering': ['patente'],
                'verbose_name_plural': 'Militares',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
                ('quantidade_vitimas', models.IntegerField()),
                ('quantidade_obitos', models.IntegerField()),
                ('descricao', models.TextField(blank=True, max_length=300)),
                ('livro', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['data_saida'],
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, max_length=300)),
                ('livro', models.CharField(max_length=100)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['data_saida'],
                'verbose_name_plural': 'Prevenções',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar')),
                ('patente_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Patente')),
            ],
            options={
                'ordering': ['data'],
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='Punicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('dias', models.PositiveSmallIntegerField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar')),
            ],
            options={
                'verbose_name_plural': 'Punições',
            },
        ),
        migrations.CreateModel(
            name='Quartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_Quartel')),
            ],
            options={
                'verbose_name_plural': 'Quarteis',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recompensador', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Dispensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de dispensa',
            },
        ),
        migrations.CreateModel(
            name='Tipo_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Area_ocorrencia')),
            ],
            options={
                'verbose_name_plural': 'Tipos de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de patente',
            },
        ),
        migrations.CreateModel(
            name='Tipo_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Area_prevencao')),
            ],
            options={
                'verbose_name_plural': 'Tipos de prevenção',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Punicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de punição',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de recompensa',
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie_tipo', models.CharField(max_length=300)),
                ('combustivel', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=300)),
                ('ano_fab', models.PositiveSmallIntegerField()),
                ('ano_mod', models.PositiveSmallIntegerField()),
                ('cor_predominante', models.CharField(max_length=50)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Quartel')),
            ],
        ),
        migrations.AddField(
            model_name='recompensa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Recompensa'),
        ),
        migrations.AddField(
            model_name='punicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Punicao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='atendimento',
            field=models.ManyToManyField(to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Bairro_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='tipo',
            field=models.ManyToManyField(to='bombeiros.Tipo_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='viaturas',
            field=models.ManyToManyField(to='bombeiros.Viatura'),
        ),
        migrations.AddField(
            model_name='patente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Patente'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='atendimento',
            field=models.ManyToManyField(to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Bairro_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo',
            field=models.ManyToManyField(to='bombeiros.Tipo_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='viaturas',
            field=models.ManyToManyField(to='bombeiros.Viatura'),
        ),
        migrations.AddField(
            model_name='militar',
            name='lotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='militar',
            name='naturalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_Natal'),
        ),
        migrations.AddField(
            model_name='militar',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Patente'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Dispensa'),
        ),
        migrations.AddField(
            model_name='cidade_quartel',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cidade_prevencao',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cidade_ocorrencia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cidade_natal',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cargo_funcao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Secao'),
        ),
        migrations.AddField(
            model_name='bairro_prevencao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_prevencao'),
        ),
        migrations.AddField(
            model_name='bairro_ocorrencia',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_ocorrencia'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Viatura'),
        ),
    ]
