# Generated by Django 2.0.5 on 2018-05-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombeiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometro', models.CharField(max_length=50)),
                ('combustivel', models.CharField(max_length=50)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Area_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas de Prevenção',
            },
        ),
        migrations.CreateModel(
            name='Bairro_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bairros de Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Bairro_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bairros de Prevenções',
            },
        ),
        migrations.CreateModel(
            name='Cidade_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Cidade_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades de Prevenções',
            },
        ),
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('data_parte', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['data_parte'],
            },
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Férias',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, max_length=300)),
                ('livro', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, max_length=300)),
                ('livro', models.CharField(max_length=100)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Prevenções',
                'ordering': ['data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Promoções',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Punicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('dias', models.PositiveSmallIntegerField()),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Punições',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recompensador', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Dispensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Dispensa',
            },
        ),
        migrations.CreateModel(
            name='Tipo_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Area_ocorrencia')),
            ],
            options={
                'verbose_name_plural': 'Tipos de ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Tipo_prevencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Area_prevencao')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Prevenção',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Punicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Punição',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Recompensa',
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie_tipo', models.CharField(max_length=300)),
                ('combustivel', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=300)),
                ('ano_fab', models.PositiveSmallIntegerField()),
                ('ano_mod', models.PositiveSmallIntegerField()),
                ('cor_predominante', models.CharField(max_length=50)),
                ('documento', models.FileField(blank=True, upload_to='')),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cargo_funcao',
            options={'verbose_name_plural': 'Cargos/Funções'},
        ),
        migrations.AlterModelOptions(
            name='cidade_natal',
            options={'verbose_name_plural': 'Cidades onde residem'},
        ),
        migrations.AlterModelOptions(
            name='cidade_quartel',
            options={'verbose_name_plural': 'Cidades onde existe Quartel'},
        ),
        migrations.AlterModelOptions(
            name='militar',
            options={'ordering': ['patente'], 'verbose_name_plural': 'Militares'},
        ),
        migrations.AlterModelOptions(
            name='patente',
            options={'ordering': ['nivel']},
        ),
        migrations.AlterModelOptions(
            name='quartel',
            options={'verbose_name_plural': 'Quarteis'},
        ),
        migrations.AlterModelOptions(
            name='secao',
            options={'verbose_name_plural': 'Seções'},
        ),
        migrations.AlterModelOptions(
            name='tipo_patente',
            options={'verbose_name_plural': 'Tipos de patente'},
        ),
        migrations.AlterField(
            model_name='cargo_funcao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargo_funcao',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cidade_natal',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cidade_quartel',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='militar',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='militar',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='secao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='secao',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipo_patente',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='viatura',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Recompensa'),
        ),
        migrations.AddField(
            model_name='punicao',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='punicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Punicao'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='patente_nova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Patente'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='atendimento',
            field=models.ManyToManyField(to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Bairro_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='tipo',
            field=models.ManyToManyField(to='bombeiros.Tipo_prevencao'),
        ),
        migrations.AddField(
            model_name='prevencao',
            name='viaturas',
            field=models.ManyToManyField(to='bombeiros.Viatura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='atendimento',
            field=models.ManyToManyField(to='bombeiros.Quartel'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Bairro_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo',
            field=models.ManyToManyField(to='bombeiros.Tipo_ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='viaturas',
            field=models.ManyToManyField(to='bombeiros.Viatura'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Tipo_Dispensa'),
        ),
        migrations.AddField(
            model_name='cidade_prevencao',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='cidade_ocorrencia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Estado'),
        ),
        migrations.AddField(
            model_name='bairro_prevencao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_prevencao'),
        ),
        migrations.AddField(
            model_name='bairro_ocorrencia',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Cidade_ocorrencia'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Militar'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombeiros.Viatura'),
        ),
    ]
